apiVersion: v1
kind: Service
metadata:
  name: service-feed
  labels:
    run: backend-feed
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    run: backend-feed
